Sarveshgithub/sfdc-lwc-lightning-datatable

- main/default/classes/RelatedList_Test.cls
countRecords had changed parameter(the parameter is now expected to be an object api name and not a query)
> Fixes bug in test method countRecords_Test

- README.md
- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.html
- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.js
> Buttons configuration for #11 + enhance readme

- README.md
- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.html
- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.js
- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.js-meta.xml
make button configuration easy and unique(not based on event, or method) + documentation for button configuration
> Dev : make button configuration easy and unique(not based on event, or method)

- README.md
- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.html
- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.js
- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.js-meta.xml
> optional pagination, view all / expand buttons #21

- README.md
- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.html
- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.js
> Added sorting

- README.md
- force-app/main/default/classes/RelatedList.cls
- force-app/main/default/classes/RelatedList_Test.cls
- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.html
- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.js
- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.js-meta.xml
Everything is implemented, the search bar is displayed by default.
Documentation is up to date
> add search bar on demand #30

- README.md
> update doc label override #62

- force-app/main/default/labels/CustomLabels.labels-meta.xml
- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.js
- manifest/package.xml
[[](url)](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/issues/108)
> Labels for toast message

- README.md
- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.html
- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.js
- force-app/main/default/lwc/lwcRelatedList/lwcRelatedListHelper.js
This PR will fix pagination, and sort on search, i.e pagination, and sort functionality will be disabled on search
Fixes # (https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/issues/119, https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/issues/120)
> fix search

- force-app/main/default/classes/RelatedList.cls
add type 'date-local' for 'date' type
Fixes #143
> #143 fix simple date edit

- README.md
- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.js
update documentation(buttons, columns override) and in an old comment in the lwc related list component
documentation update
I tested every JSON configs.
> update documentation(buttons, columns override)

- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.js-meta.xml
Expose the component to flow screen and fix community prop (the props were not visible).
Fixes #151
> #151 expose to flow screen and fix community props

- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.js
-   [ ] Test A
-   [ ] Test B
-   [ ] I have …
> add recordtype check #186

- force-app/main/default/lwc/datatableLookup/datatableLookup.js
- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.html
- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.js
Fix draft merge + allow to empty lookup
Fixes #167
Related PR #192
-  edit only standard fields
-  edit standard columns then edit a custom datatype on one row
-  edit standard columns then edit a custom datatype on several rows
- edit custom datatype then edit a standard column on one row
- edit custom datatype then edit a standard column on several columns
> #167 fix draft merge

- force-app/main/default/lwc/lwcRelatedList/lwcRelatedListHelper.js
The problem comes from format data (I have a fix for this issue, I'll do a PR), only the first column is taken into account (Name)
@Sarveshgithub When you'll merge this change you could change the last release to the last commit of the Master branch
Fixes #203
-   Bug fix (non-breaking change which fixes an issue)
-   [ ] query One field of related record
-   [ ] query Multiple field  of related record
> Update _formatData #203

- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.js
-   [ ] Test A
-   [ ] Test B
-   [ ] I have …
> #206 : fix counter

- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.html
-   [ ] Test A
-   [ ] Test B
-   [ ] I have …
> add refresh [ Feature ] - Refresh button #211

- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.js-meta.xml
-   [ ] Test A
-   [ ] Test B
-   [ ] I have …
> add default limit = 10 #216

- force-app/main/default/classes/RelatedList.cls
@Sarveshgithub done
override percent type with percent-fixed type
Fixes #224
-   Bug fix (non-breaking change which fixes an issue)
-   test with value with fields setup with decimals places (0.5 %, 50.2 %, 100.5 %) => ok
-   test with value > 100 (150%) => ok
-  test with basic value (10%) => ok
> #224 fix percent field display

- README.md
#232
@Sarveshgithub I tested on one sandbox that was causing the issue it works now
> Update README.md deploy button #232

- force-app/main/default/classes/IconUtils.cls
-   [ ] Test A
-   [ ] Test B
-   [ ] I have …
> added if condition

- force-app/main/default/classes/RelatedList.cls
-   [ ] Test A
-   [ ] Test B
-   [ ] I have …
> removed wrapper that not needed

- README.md
- force-app/main/default/classes/RelatedList.cls
- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.js
- force-app/main/default/lwc/lwcRelatedList/lwcRelatedList.js-meta.xml
- package.json
Allow aggregate functions + documentation link to format dates.
@Sarveshgithub **I had to disable pre-commit scripts they don't work (error at the very beginning of each files for .md, .cls, .js, .xml files)**
Fixes #252
-   [x] New feature (non-breaking change which adds functionality)
-   [x] SELECT AccountId, count(Id) FROM CONTACT GROUP BY AccountId
-   [x] …
> Dev aggregates functions #252
